AWSTemplateFormatVersion: '2010-09-09'
Description: Integration test - monitor with Datadog notebook runbook asset

Parameters:
  NotebookId:
    Type: String
    Description: Existing Datadog notebook ID

Resources:
  NotebookRunbookMonitor:
    Type: Datadog::Monitors::Monitor
    Properties:
      Type: query alert
      Query: avg(last_5m):avg:system.cpu.system{*} > 100
      Name: CFN Integration Test - Notebook Runbook
      Message: Integration test monitor with notebook runbook asset
      Options:
        Thresholds:
          Critical: 100
      Assets:
        - Category: runbook
          Name: Datadog Notebook Runbook
          Url: !Sub /notebook/${NotebookId}/runbook
          ResourceType: notebook
          ResourceKey: !Ref NotebookId

Outputs:
  MonitorId:
    Value: !GetAtt NotebookRunbookMonitor.Id
