name: Run Contract Tests

on:
  pull_request:
    branches:
      - master

concurrency:
  group: contract-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        resource: [
            datadog-dashboards-dashboard-handler,
            datadog-monitors-monitor-handler,
            datadog-monitors-downtime-handler,
            datadog-integrations-aws-handler,
            datadog-iam-user-handler
        ]
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: aws-actions/setup-sam@v1
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Deps
      run: pip install --disable-pip-version-check -e ./datadog-cloudformation-common-python[build]
    - name: Run Tests
      run: |
        mkdir ~/.cfn-cli
        echo "{\"DatadogCredentials\":{\"ApiKey\":\"${DD_TEST_CLIENT_API_KEY}\",\"ApplicationKey\":\"${DD_TEST_CLIENT_APP_KEY}\"}}" > ~/.cfn-cli/typeConfiguration.json
        cd ${{ matrix.resource }}
        sam local start-lambda &
        cfn test
      env:
        DD_TEST_CLIENT_API_KEY: ${{ secrets.DD_TEST_CLIENT_API_KEY }}
        DD_TEST_CLIENT_APP_KEY: ${{ secrets.DD_TEST_CLIENT_APP_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}