name: Run Contract Tests

env:
  GIT_AUTHOR_EMAIL: "packages@datadoghq.com"
  GIT_AUTHOR_NAME: "ci.datadog-cloudformation-resources"

on:
  pull_request:
    branches:
      - master

concurrency:
  group: contract-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  find_modified_resources:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get changed files
      id: changed_files
      uses: tj-actions/changed-files@v8.4
    outputs:
      changed_files: ${{ steps.changed_files.outputs.all_changed_files }}

  test:
    needs: find_modified_resources
    strategy:
      fail-fast: false
      matrix:
        resource:
          - datadog-dashboards-dashboard-handler
          - datadog-monitors-monitor-handler
          - datadog-monitors-downtime-handler
          - datadog-integrations-aws-handler
          - datadog-slos-slo-handler
#         - datadog-iam-user-handler
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
    - name: Install Python
      if: contains(needs.find_modified_resources.outputs.changed_files, matrix.resource)
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: aws-actions/setup-sam@v1
      if: contains(needs.find_modified_resources.outputs.changed_files, matrix.resource)
    - name: Checkout code
      if: contains(needs.find_modified_resources.outputs.changed_files, matrix.resource)
      uses: actions/checkout@v3
    - name: Install Deps
      if: contains(needs.find_modified_resources.outputs.changed_files, matrix.resource)
      run: pip install --disable-pip-version-check -e ./datadog-cloudformation-common-python[build]
    - name: Install pre-commit
      run: python -m pip install pre-commit
    - name: Build Package
      if: contains(needs.find_modified_resources.outputs.changed_files, matrix.resource)
      run: |
        cd ${{ matrix.resource }}
        cfn submit --dry-run --no-role
    - name: Create Type Configuration
      if: contains(needs.find_modified_resources.outputs.changed_files, matrix.resource)
      run: |
        mkdir ~/.cfn-cli
        echo "{\"DatadogCredentials\":{\"ApiKey\":\"${DD_TEST_CLIENT_API_KEY}\",\"ApplicationKey\":\"${DD_TEST_CLIENT_APP_KEY}\"}}" > ~/.cfn-cli/typeConfiguration.json
      env:
        DD_TEST_CLIENT_API_KEY: ${{ secrets.DD_TEST_CLIENT_API_KEY }}
        DD_TEST_CLIENT_APP_KEY: ${{ secrets.DD_TEST_CLIENT_APP_KEY }}
    - name: Check generated files are up-to-date
      if: contains(needs.find_modified_resources.outputs.changed_files, matrix.resource)
      run: |
        cd ${{ matrix.resource }}
        cfn generate
        pre-commit run --all-files
        set +e
        git diff --exit-code
        if [ $? -ne 0  ]; then
          echo "'cfn generate' generated some changes. Run it locally and commit changes."
        fi
        set -e
    - name: Run Tests
      if: contains(needs.find_modified_resources.outputs.changed_files, matrix.resource)
      run: |
        cd ${{ matrix.resource }}
        sam local start-lambda &
        cfn test --role-arn arn:aws:iam::088054601418:role/cf-contract-tests-ci
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}